server:
  port: 8082

spring:
  application:
    name: gimnasio-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para el servicio de miembros
        - id: miembros-service
          uri: lb://MIEMBROS-SERVICE
          predicates:
            - Path=/api/miembros/**
          filters:
            - RewritePath=/api/miembros/(?<path>.*), /$\{path}

        # Ruta para el servicio de clases
        - id: clases-service
          uri: lb://CLASES-SERVICE
          predicates:
            - Path=/api/clases/**
          filters:
            - RewritePath=/api/clases/(?<path>.*), /$\{path}

        # Ruta para el servicio de entrenadores
        - id: entrenadores-service
          uri: lb://ENTRENADORES-SERVICE
          predicates:
            - Path=/api/entrenadores/**
          filters:
            - RewritePath=/api/entrenadores/(?<path>.*), /$\{path}

        # Ruta para el servicio de equipos
        - id: equipos-service
          uri: lb://EQUIPOS-SERVICE
          predicates:
            - Path=/api/equipos/**
          filters:
            - RewritePath=/api/equipos/(?<path>.*), /$\{path}

        # Ruta para el servicio de pagos
        - id: pagos-service
          uri: lb://pagos-service
          predicates:
            - Path=/api/pagos/**
          filters:
            - RewritePath=/api/pagos/(?<path>.*), /$\{path}

        # Ruta para el resumen de miembro (agregación)
        - id: miembro-resumen
          uri: no://op
          predicates:
            - Path=/api/resumen/miembro/**
          filters:
            - name: MiembroResumenFilter
              args:
                baseUri: lb://miembros-service
                clasesUri: lb://clases-service
                pagosUri: lb://pagos-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gimnasio

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always